services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://ella.db.elephantsql.com:5432/ldctrnpn?ApplicationName=TrackeroDevTeam
      DB_USER: ldctrnpn
      DB_PASSW: 18_xsgAF-t47YXXPUyvN74MyYaxafd0Q

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend
